version: "2" # 설치된 docker 버전에 따라 다릅니다!
services:
  server:
    container_name: server
    image: lopun/all-compilers:0.1
    ports:
      - "16200:8080" # 연결할 포트
    environment: # 환경변수 설정
      - DB_HOST=mongo
      - DB=test
    networks: # 각 컨테이너를 연결하는 네트워크
      - backend
    volumes:
      # - /home/sbagi/webditor/:/home/webditor/
      - C:\Users\lopun\CS\webditor:/home/webditor
    command: /home/webditor/docker_config/start_up.sh
    links:
      - mongodb
    tty: true
    stdin_open: true

  mongodb:
    container_name: mongo
    image: mongo
    expose:
      - "27017"
    volumes:
      # - /home/sbagi/webditor_mongodata:/data/db # volume을 만들어두지 않으면 컨테이너가 매번 종료될 때마다 데이터가 초기화 되므로 따로 볼륨으로 관리한다.
      - C:\Users\lopun\CS\webditor_mongodata:/data/db
    networks:
      - backend # 앱 서버와 같은 네트워크에 연결
      # 만약 이 항목을 넣지 않으면 연결이 없다는 에러가 발생함

networks: # 가장 기본적인 bridge 네트워크
  backend:
    driver: bridge